## Worked on during a community livestream!
## Go watch it @ twitch.tv/trhrichard if it's still live!

name: Build & deploy to GitHub Pages

run-name: Deploy ${{ github.sha }} to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"

      - name: Caching
        uses: actions/cache@v4
        with:
          path: |
            .astro/
            node_modules/
            dist/
          key: deploy-cache
          restore-keys: |
            *-check-cache

      - name: Install dependencies
        run: pnpm install --frozen-lockfile # --frozen-lockfile because I want to have anything done reproducible on my side as much as possible

      - name: Build site
        run: pnpm build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
